name: CICD

on:
    push: 
        branches:
            - main
    pull_request: 
        branches:
            - main
    workflow_dispatch:

env: 
    EPITECH_REPO: "git@github.com:EpitechPGE3-2026/G-ING-500-PAR-5-1-rtype-12.git"

jobs:
  build-project-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: Install dependencies
        run: |
            sudo apt-get update 
      - name: Configure and build
        run: | 
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

  build-project-Window:
    runs-on: windows-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: Setup Windows tools
        run: |
          echo "Using Visual Studio and CMake preinstalled on windows-latest"
      - name: Configure and build
        shell: powershell
        run: |
          cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -- /m

  push-to-mirror:
    needs: [build-project-Linux , build-project-Window]
    if: github.repository == 'aludnier/R-Type_Mirror'
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: "actions/checkout@v4"
          with:
            fetch-depth: 0
        - name: Push to Epitech Repository
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: ${{ env.EPITECH_REPO }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

